// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://eirc.app/",
        "contact": {
            "name": "API System Support",
            "url": "https://eirc.app/",
            "email": "mingzong.lyu@gmail.com"
        },
        "license": {
            "name": "AGPL 3.0",
            "url": "https://www.gnu.org/licenses/agpl-3.0.en.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/authority/v1.0/account": {
            "get": {
                "description": "條件使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "條件搜尋使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "組織ID",
                        "name": "organizationID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "帳號",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "中文名稱",
                        "name": "chineseName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色名稱",
                        "name": "roleName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "目前頁數,請從1開始帶入",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "一次回傳比數,請從1開始帶入,最高上限20",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/accounts.List"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "新增使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "新增使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增使用者",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.Created"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/authority/v1.0/account/{accountID}": {
            "get": {
                "description": "取得單一使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "取得單一使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "使用者ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/accounts.Single"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除單一使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "刪除單一使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "使用者ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "patch": {
                "description": "更新單一使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "更新單一使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "使用者ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新使用者",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.Updated"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/authority/v1.0/companies": {
            "get": {
                "description": "條件公司行號",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "條件搜尋公司行號",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公司名稱",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "公司統一編號",
                        "name": "uniform_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "目前頁數,請從1開始帶入",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "一次回傳比數,請從1開始帶入,最高上限20",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/companies.List"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "新增公司行號",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "新增公司行號",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增公司行號",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/companies.Created"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/authority/v1.0/companies/{companyID}": {
            "get": {
                "description": "取得單一公司行號",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "取得單一公司行號",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公司編號",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/companies.Single"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除公司",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "刪除公司",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公司編號",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "patch": {
                "description": "更新單一使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Companies"
                ],
                "summary": "更新單一使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "公司編號",
                        "name": "companyID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新公司",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/companies.Updated"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/authority/v1.0/login/refresh": {
            "post": {
                "description": "換新的令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "換新的令牌",
                "parameters": [
                    {
                        "description": "登入帶入",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jwe.Refresh"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/jwe.Token"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/authority/v1.0/login/web": {
            "post": {
                "description": "使用者登入",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "使用者登入",
                "parameters": [
                    {
                        "description": "登入帶入",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/logins.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/jwe.Token"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/authority/v1.0/account": {
            "get": {
                "description": "條件使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "條件搜尋使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "組織ID",
                        "name": "organizationID",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "帳號",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "中文名稱",
                        "name": "chineseName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "角色名稱",
                        "name": "roleName",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "目前頁數,請從1開始帶入",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "一次回傳比數,請從1開始帶入,最高上限20",
                        "name": "limit",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/accounts.List"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "新增使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "新增使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "新增使用者",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.Created"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/authority/v1.0/account/{accountID}": {
            "get": {
                "description": "取得單一使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "取得單一使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "使用者ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "$ref": "#/definitions/accounts.Single"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "刪除單一使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "刪除單一使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "使用者ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "patch": {
                "description": "更新單一使用者",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Account"
                ],
                "summary": "更新單一使用者",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWE Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "使用者ID",
                        "name": "accountID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新使用者",
                        "name": "*",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/accounts.Updated"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功後返回的值",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.SuccessfulMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "body": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "415": {
                        "description": "必要欄位帶入錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "伺服器非預期錯誤",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/code.ErrorMessage"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "detailed": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "accounts.Created": {
            "type": "object",
            "required": [
                "account",
                "name",
                "password"
            ],
            "properties": {
                "account": {
                    "description": "帳號",
                    "type": "string"
                },
                "bonita_manager_id": {
                    "description": "BonitaUserID",
                    "type": "string"
                },
                "bonita_user_id": {
                    "description": "[ 6] bonita_user_id                                         TEXT                 null: true   primary: false  isArray: false  auto: false  col: TEXT            len: -1      default: []",
                    "type": "string"
                },
                "company_id": {
                    "description": "公司ID",
                    "type": "string"
                },
                "created_account": {
                    "description": "創建者帳號",
                    "type": "string"
                },
                "email": {
                    "description": "電子郵件",
                    "type": "string"
                },
                "enabled": {
                    "description": "bonita是否啟用使用者",
                    "type": "string"
                },
                "manager_id": {
                    "description": "bonita父部門",
                    "type": "string"
                },
                "name": {
                    "description": "中文名稱",
                    "type": "string"
                },
                "password": {
                    "description": "密碼",
                    "type": "string"
                },
                "phone": {
                    "description": "角色編號\nRoleID string ` + "`" + `json:\"role_id\"` + "`" + `\n所屬部門\nDep string ` + "`" + `json:\"dep\" binding:\"required\" validate:\"required\"` + "`" + `\n電話",
                    "type": "string"
                },
                "userName": {
                    "description": "bonita顯示的名稱",
                    "type": "string"
                }
            }
        },
        "accounts.List": {
            "type": "object",
            "required": [
                "limit",
                "page"
            ],
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "account": {
                                "description": "帳號",
                                "type": "string"
                            },
                            "account_id": {
                                "description": "編號",
                                "type": "string"
                            },
                            "bonita_manager_id": {
                                "description": "BonitaUserID",
                                "type": "string"
                            },
                            "bonita_user_id": {
                                "description": "bonita_user_id",
                                "type": "string"
                            },
                            "company_id": {
                                "description": "公司ID",
                                "type": "string"
                            },
                            "email": {
                                "description": "電子郵件",
                                "type": "string"
                            },
                            "name": {
                                "description": "中文名稱",
                                "type": "string"
                            },
                            "phone": {
                                "description": "角色編號\nRoleID string ` + "`" + `json:\"role_id,omitempty\"` + "`" + `\n所屬部門\nDep string ` + "`" + `json:\"dep,omitempty\"` + "`" + `\n電話",
                                "type": "string"
                            },
                            "status": {
                                "description": "帳號狀態",
                                "type": "boolean"
                            }
                        }
                    }
                },
                "limit": {
                    "description": "筆數(請從1開始帶入,最高上限20)",
                    "type": "integer"
                },
                "page": {
                    "description": "頁數(請從1開始帶入)",
                    "type": "integer"
                },
                "pages": {
                    "description": "總頁數",
                    "type": "integer"
                },
                "total": {
                    "description": "總筆數",
                    "type": "integer"
                }
            }
        },
        "accounts.Single": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "帳號",
                    "type": "string"
                },
                "account_id": {
                    "description": "編號",
                    "type": "string"
                },
                "bonita_manager_id": {
                    "description": "BonitaUserID",
                    "type": "string"
                },
                "bonita_user_id": {
                    "description": "[ 6] bonita_user_id                                         TEXT                 null: true   primary: false  isArray: false  auto: false  col: TEXT            len: -1      default: []",
                    "type": "string"
                },
                "company_id": {
                    "description": "公司ID",
                    "type": "string"
                },
                "created_at": {
                    "description": "創建時間",
                    "type": "string"
                },
                "created_by": {
                    "description": "創建者",
                    "type": "string"
                },
                "email": {
                    "description": "電子郵件",
                    "type": "string"
                },
                "is_deleted": {
                    "description": "是否刪除",
                    "type": "boolean"
                },
                "name": {
                    "description": "中文名稱",
                    "type": "string"
                },
                "password": {
                    "description": "密碼",
                    "type": "string"
                },
                "phone": {
                    "description": "角色編號\nRoleID string ` + "`" + `json:\"role_id,omitempty\"` + "`" + `\n所屬部門\nDep string ` + "`" + `json:\"dep,omitempty\"` + "`" + `\n電話",
                    "type": "string"
                },
                "status": {
                    "description": "帳號狀態",
                    "type": "boolean"
                },
                "updated_at": {
                    "description": "更新時間",
                    "type": "string"
                },
                "updated_by": {
                    "description": "更新者",
                    "type": "string"
                }
            }
        },
        "accounts.Updated": {
            "type": "object",
            "properties": {
                "bonita_manager_id": {
                    "description": "BonitaUserID",
                    "type": "string"
                },
                "bonita_user_id": {
                    "description": "bonita_user_id",
                    "type": "string"
                },
                "company_id": {
                    "description": "組織ID",
                    "type": "string"
                },
                "created_account": {
                    "description": "創建者帳號",
                    "type": "string"
                },
                "email": {
                    "description": "電子郵件",
                    "type": "string"
                },
                "enabled": {
                    "description": "bonita是否啟用使用者",
                    "type": "string"
                },
                "manager_id": {
                    "description": "bonita父部門",
                    "type": "string"
                },
                "name": {
                    "description": "中文名稱",
                    "type": "string"
                },
                "password": {
                    "description": "密碼",
                    "type": "string"
                },
                "phone": {
                    "description": "角色編號\nRoleID *string ` + "`" + `json:\"role_id,omitempty\"` + "`" + `\n所屬部門\nDep string ` + "`" + `json:\"dep\" ` + "`" + `\n電話",
                    "type": "string"
                },
                "status": {
                    "description": "帳號狀態",
                    "type": "boolean"
                },
                "userName": {
                    "description": "bonita顯示的名稱",
                    "type": "string"
                }
            }
        },
        "code.ErrorMessage": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "回傳代碼",
                    "type": "integer"
                },
                "detailed": {
                    "description": "詳細錯誤內容"
                },
                "message": {
                    "description": "錯誤回傳訊息",
                    "type": "string"
                },
                "timestamp": {
                    "description": "錯誤時間",
                    "type": "string",
                    "example": "2021-07-29T07:23:47Z"
                }
            }
        },
        "code.SuccessfulMessage": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "正確回傳內容"
                },
                "code": {
                    "description": "回傳代碼",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "錯誤時間",
                    "type": "string",
                    "example": "2021-07-29T07:23:47Z"
                }
            }
        },
        "companies.Created": {
            "type": "object",
            "required": [
                "name",
                "uniform_number"
            ],
            "properties": {
                "name": {
                    "description": "公司名稱",
                    "type": "string"
                },
                "uniform_number": {
                    "description": "公司統一編號",
                    "type": "integer"
                }
            }
        },
        "companies.List": {
            "type": "object",
            "required": [
                "limit",
                "page"
            ],
            "properties": {
                "companies": {
                    "description": "多筆公司",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "company_id": {
                                "description": "公司編號",
                                "type": "string"
                            },
                            "created_at": {
                                "description": "創建時間",
                                "type": "string"
                            },
                            "created_by": {
                                "description": "創建者",
                                "type": "string"
                            },
                            "name": {
                                "description": "公司名稱",
                                "type": "string"
                            },
                            "uniform_number": {
                                "description": "公司統一編號",
                                "type": "integer"
                            }
                        }
                    }
                },
                "limit": {
                    "description": "筆數(請從1開始帶入,最高上限20)",
                    "type": "integer"
                },
                "page": {
                    "description": "頁數(請從1開始帶入)",
                    "type": "integer"
                },
                "pages": {
                    "description": "總頁數",
                    "type": "integer"
                },
                "total": {
                    "description": "總筆數",
                    "type": "integer"
                }
            }
        },
        "companies.Single": {
            "type": "object",
            "properties": {
                "company_id": {
                    "description": "公司編號",
                    "type": "string"
                },
                "created_at": {
                    "description": "創建時間",
                    "type": "string"
                },
                "created_by": {
                    "description": "創建者",
                    "type": "string"
                },
                "name": {
                    "description": "公司名稱",
                    "type": "string"
                },
                "uniform_number": {
                    "description": "公司統一編號",
                    "type": "integer"
                },
                "updated_at": {
                    "description": "更新時間",
                    "type": "string"
                },
                "updated_by": {
                    "description": "更新者",
                    "type": "string"
                }
            }
        },
        "companies.Updated": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "公司名稱",
                    "type": "string"
                },
                "uniform_number": {
                    "description": "公司統一編號",
                    "type": "integer"
                }
            }
        },
        "jwe.Refresh": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string"
                }
            }
        },
        "jwe.Token": {
            "type": "object",
            "properties": {
                "access_token": {
                    "description": "授權令牌",
                    "type": "string"
                },
                "refresh_token": {
                    "description": "刷新令牌",
                    "type": "string"
                }
            }
        },
        "logins.Login": {
            "type": "object",
            "required": [
                "account",
                "company_id",
                "password"
            ],
            "properties": {
                "account": {
                    "description": "帳號",
                    "type": "string"
                },
                "company_id": {
                    "description": "公司ID",
                    "type": "string"
                },
                "password": {
                    "description": "密碼",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "api.eirc.app",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "hsmaster SYSTEM API",
	Description:      "企業系統整合管理平台",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
